---
title: "Extra Credit 3"
description: Instructions for extra credit three.
navbar: false
date: 08-24-2026
editor: source
format:
  html: 
    code-fold: true
    html-math-method: katex
---

After reading one book below, create a video essay that summarizes the book, provide a brief analysis in supporting or opposing the book, and connect key elements of the book to your every day life. The video essay should be 10 minutes being narrated by your own voice. Use visual aids, such as a powerpoint presentation, to highlight your main findings, and how it relates to your own life. Not all books are available through the Broome Library.

**Books:**

-   Empire of AI
    -   Karen Hao

-   The Last Human Job
    -   Allison Pugh

-   The Book of Why
    -   Judea Pearl

-   Algorithms of Oppression
    -   Safiya Umoja Noble

-   Data Feminism
    -   Catherine D'Ignazio and Lauren Klein

-   Weapons of Math Destruction
    -   Cathy O'Niel

-   Invisible Women : Data bias in a world designed for men
    -   Caroline Criado Perez

-   Factfulness: Ten reasons we're wrong about the world... and why things are better than you think
    -   Hans Rosling

-   Artificial Unintelligence: How computers misunderstand the world
    -   Merideth Broussard

-   Technically Wrong: sexist apps, biased algorithms, and other threats of toxic tech
    -   Sara Wachter-Boettcher

-   Unmasking AI: My mission to protect what is human in a world of machines
    - Joy Buolamwini


-   The Eye of the Master: A social history of artificial intelligence
    - Matteo Pasquinelli

-   **OR ANY Book Approved By Me (Deadline for Approval by October 23, 2026)**

**Video Essay Guidelines:**

-   10 Minutes Long

-   Use of visual aids

-   Must show your screen and embed yourself presenting in the video.
    - Recommend using OBS Studio for screen capturing and video of yourself.

-   **Due 12/5/2026**


**Worth 2 final grade percentage points.**