---
title: "Syllabus"
editor: source
navbar: false
format:
  html: 
    code-fold: true
    html-math-method: katex
    toc: false
  typst:
    margin:
      x: 1cm
      y: 1cm
---

## Math 201: Elementary Statistics

### Course Information

**Term:** Fall 2026

**Instructor:** Isaac Quintanilla Salinas

**Email:** isaac.qs\@csuci.edu

**Office Location:** Marin Hall 2326

**Office Hours:** TBD

**Lecture:** 

| Sec | Time | Location |
|:----|:-----|:---------|
| 001 | T/TH 10:30 AM to 11:45 PM | Gateway 2501 |
| 001 | T/TH 1:30 to 2:45 PM | Gateway 2501 |


**Website:** Canvas (CI Learn)

### Course Description

Critical reasoning using a quantitative and statistical, problem-solving approach to solving real-world problems. Topics include: probability and statistics, sample data, probability and empirical data distributions, sampling techniques, estimation and hypothesis testing, ANOVA, and correlation and regression analysis. Students will use standard statistical software to analyze real-world and simulated data. GenEd: 2

### Learning Outcomes


- Apply quantitative problem-solving skills to various problems and issues
- Select, apply and interpret descriptive statistics in an appropriate fashion
- Select, apply and interpret hypothesis testing methods in an appropriate fashion
- Reason both inductively and deductively with quantitative information and data
use statistical software to conduct statistical analysis of real-world and simulated data
- Organize and express ideas clearly and convincingly in oral and written form
- (GE 2.1) Solve problems using mathematical methods
- (GE 2.2) Use graphs, tables, etc. to represent and explain mathematical models and/or quantitative data.


### Recommended Textbook

[Introduction to Modern Statistics](https://openintrostat.github.io/ims/) (IMS)

### Required Software

Install [Google Chrome](https://www.google.com/chrome/) or any other chromium-based web browser. Used to access google assignments and VoiceThreads. 

### Course Grading

| Category             | Percentage |
|:---------------------|:-----------|
| Discussion Posts     | 10%        |
| Classwork            | 15%        |
| Video Assignments    | 20%        | 
| Notebook Assignments | 25%        |
| Exam 1               | 10%        |
| Exam 2               | 10%        |
| Exam 3               | 10%        |
: Course Grading


At the end of the quarter, course grades will be assigned according to the following scale:

| Percentagae | Grade |
|:------------|:------|
| 90 - 100    | A     |
| 80 - <90    | B     |
| 70 - <80    | C     |
| 60 - <70    | D     |
| <60         | F     |
: Grade Scheme

### Class Attendance

Students are expected to attend in-person to class to learn the material.

### Canvas

Students are expected to check the course Canvas page 3-4 times a week to view assignments, announcements, and other course-related materials.

#### Discussion Posts

Discussion posts are designed to continue the conversation based on the video assignments. No late posts will be accepted. Discussion posts will be due every Monday at 11:59 PM.

#### Classwork Assignments

Classwork assignmets are designed to give you an opportunity to practice conceptual topics from the  video assignments. The assignments will require you to program in R. The 3 lowest classwork assignments will be dropped. Classwork assignments will be due every Friday at 11:59 PM.


#### Video Assignments

Videos are used to teach statistical concepts related to the course. Students are expected to watch at least one video a week. The videos are implemented using VoiceThreads. The 3 lowest video assignments will be dropped. Video assignments will be due every Sunday at 11:59 PM.


#### Notebook Assignments

Notebook assignments are designed to expand your statistical knowledge. These will be completed in Google Colab which can be accessed from Canvas. There is one notebook assignments every week that you can be completed during class time. Notebook assignments will be due on Friday at 11:59 PM every week. No late notebook assignments will be accepted. The 3 lowest notebook assignments will be dropped.


#### Exams

There will be three in exams. Exam #1 will be on September 29, 2026, Exam #2 will be on November 10, 2026, and **Exam #3 will be on 12/8 from 10:30 AM to 12:30 PM (Sec 02) or 12/10 from 8-10 AM (Sec 01) in Gateway 2501.** While the exams are not considered cumulative, the material builds on each other. Developing a strong understanding of the material through out the course is important for your success. At the end of the semester, your lowest exam grade will be replaced by your median average of all 3 exam grades. This course will operate under a zero-tolerance policy. These will be paper-based exams taken in person. Talking during the time of the exam, sharing materials, looking at another students' exam, or not following directions given will be subject to the University's academic integrity policy.

#### Extra Credit

There will be **3** extra credit opportunities worth a total of 5% of your overall grade. (There are no make-ups for missed extra credit assignments!) More information will be provided on the extra credit assignments on a later date. Information on the extra credit can be found [here](ec.html).

### Class Schedule

The following outline may be subject to change. Any changes will be announced in class.

| Week          | Topic                        | Reading         | CW DUE | Video Due | NB Due |
|:--------------|:-----------------------------|-----------------|--------|-----------|--------|
| **1** (8/24)  | Intro to Course/Intro to R   |                 |        | 1         | 1      |
| **2** (8/31)  | Data Generating Process      | 2.1 - 2.3       | 1      | 2         | 2      |
| **3** (9/7)   | Categorical Data             | 4.1 - 4.6       | 2      | 3         | 3      |
| **4** (9/14)  | Numerical Data               | 5.1 - 5.5       | 3      | 4         | 4      |
| **5** (9/21)  | Distribution Functions       |                 | 4      |           | 5      |
| **6** (9/28)  | **Exam 1**/Linear Regression |                 |        | 5         |        |
| **7** (10/5)  | Simple Linear Regression     | 7.1-7.3         | 5      | 6         | 6      |
| **8** (10/12) | Simple Logistic Regression   | 9.1-9.2         | 6      | 7         | 7      |
| **9** (10/19) | Group Models                 | 7.2.6, 9.3      | 7      | 8         | 8      |
| **10** (10/26)| Multivariable Regression     | 8.1-8.4, 9.3    | 8      | 9         | 9      |
| **11** (11/2) | Sampling Distributions       | 13.1-13.3       | 9      |           | 10     |
| **12** (11/9) | **Exam 2**/Inference         |                 |        | 10        |        |
| **13** (11/16)| Inference                    | 11.3, 24.4-24.5 | 10     | 11        | 11     |
| **14** (11/23)| Inference/**Holiday**        |                 | 11     | 12        |        |
| **15** (11/30)| Inference                    | 24.6, 26.1      | 12     |           | 12     |
| **16** (12/7) | **Exam 3**                   |                 |        |           |        |
: Weekly Topics


### Generative Artificial Intelligence Policy

The use of generative artificial intelligence (AI) in an ethical manner is permitted for this course.

#### Permitted Uses

You may use AI for:

- Obtain clarification 

- Brainstorming ideas, examples, outlines, and strategies

- Generating questions for practice or exploration

- Identifying keywords or phrasing to match professional goals

#### Prohibited Uses

You may not:

- Submit AI-generated work 

- Use AI to complete assignments, quizzes, exams, or other assessments meant to reflect only your own work

- Use AI to generate code

Any AI-generated work will receive a 0 in the class. Severe cases will be reported to Academic Misconduct.

**You may not upload any course material to any AI platforms such as ChatGPT, Claude, Meta AI, and Google Gemini.  Exceptions are allowed for [DASS](https://www.csuci.edu/dass/)-approved services.**

## University Policies

### Syllabus Policies and Assistance

CSUCI’s [Syllabus Policies and Assistance Website](https://www.csuci.edu/studentsupport/syllabus.htm) provides important details about academic policies, campus expectations, and student support services that are all highly applicable to your success as a student both in and outside of the classroom. Ensure that you review this site on a regular basis to stay informed about the policies and resources that support your success, as campus resources or policies may change semester to semester.

### Academic Honesty

Conduct yourself with honesty and integrity. Do not submit others' work as your own. Foassignments and quizzes that allow you to work with a group, only put your name on what the group submits if you genuinely contributed to the work. Work completely independently on exams, using only the materials that are indicated as allowed. Failure to observe academic honesty results in substantial penalties that can include failing the course.

### CSUCI Basic Need

Please use the link to the Basic Needs Program on the [Syllabus Policies and Assistance website](go.csuci.edu/syllabuspolicies) for information on emergency food, housing accommodations, toiletries, and connections to critical resources. 


### CSUCI Disability Statement

If you are a student with a disability requesting reasonable accommodations in this course, you need to contact Disability Accommodations and Support Services (DASS) located on the second floor of Arroyo Hall, via email accommodations\@csuci.edu or call 805-437-3331. [All requests for reasonable accommodations require registration with DASS in advance of need](https://www.csuci.edu/dass/students/apply-for-services.htm). Faculty, students and DASS will work together regarding classroom accommodations. You are encouraged to discuss approved.

### Disruption

1.  **If I Am Out:** I will communicate via email and will hold classes asynchronously.
2.  **If You Are Out:** Contact me as soon as possible to talk about your options. Reasonable accommodations will be provided for a brief absence. With proper documentation, extended accommodations will be provided.

